### ISSUE TITLE
Question - alphabetical order and excluede tiddlers

### ISSUE THREAD

**Issue by ghost** [kookma/TW-TOC#1]
Hi, I decided to use this channel to ask you question. Is there a way to set alphabetical order of tiddlers on the same level in tree instead of order based on modification time?

Second one - is there a way to exclude tiddlers by some naming patterns, so, they will be not visible in tree?

Best regards!

**Comment by kookma** [comment]
@s-kaczmarek 

This is the right channel to raise issues and ask for features.

Q1. Could you explain more or give an example

Q2. The exclude parameter uses filter pattern so `-[tag[mytag]]`  will exclude all tiddlers in tree tagged with `mytag` and
 `-[search:title[mytitle]]` will exclude all tiddlers have `mytitle` word in their title

**Comment by ghost** [comment]
Q1: when we create tiddler with toc called "tree" and then we create tiddler called "b" with tag "tree" and after that we create tiddler called "a" with tag "tree", tiddler called "tree" will display something like that:

```
v
  b
  a
```

I would like it to display:

```
v
  a
  b
```

Q2: Thanks, works fine :)

**Comment by kookma** [comment]
This is very simple


- Open tiddler b
- click on tag pill (it is tree based on your explanation)
- drag and drop a above b
- that is all
