### ISSUE TITLE
Possible to auto open a title in TOC?

### ISSUE THREAD

**Issue by linonetwo** [kookma/TW-TOC#4]
VSCode's menu will auto open a tree when you open a file via command palette.

If you close a tree, and use ctrl+tab to open that file, the tree will also auto open to show the file. Is tw's toc possible to do this?

Or at lease can we remember the tree opened state? So in a VSCode-like layout, user don't need to reopen the tree each time when he open the wiki.

**Comment by kookma** [comment]
No TW-TOC cannot support auto open. The reason is how recognize the opened tiddler?
Is it a tiddler in $:/StoryList or under focus,...

**Comment by linonetwo** [comment]
Maybe just a tiddler's text to indicate the focus. In story river it is $:/state/focusedTiddler, on single Tiddler layout it maybe other. And assign this tiddler title to the macro.

This maybe hard with only wikitext, maybe need to involve JS...

**Comment by linonetwo** [comment]
I will use wikitext based TOC for a while, when I have time, I will write a JS based folder widget for such feature. Because I want to create a VSCode-like layout.
